### ISSUE TITLE
could you please publish it on npm?

### ISSUE THREAD

**Issue by stevermeister** [AddToCalendar/addtocalendar-bower-package#1]
we switched from bower to npm, so it would be nice if we could use your product via npm

**Comment by stephanebachelier** [comment]
+1 :)

**Comment by atc-master** [comment]
@stephanebachelier @stevermeister 
Please check out this package: https://www.npmjs.com/package/addtocalendar

```
npm install addtocalendar
```

**Comment by stevermeister** [comment]
👍
