### ISSUE TITLE
TypeError: addtocalendar.load is not a function

### ISSUE THREAD

**Issue by throrin19** [AddToCalendar/addtocalendar-bower-package#3]
Hi, I test to use it with require.JS but I have this error : 

```
TypeError: addtocalendar.load is not a function
```

I try to use it differently but it does not works. 

And I notify you don't include the css in this package

**Comment by sunny0825** [comment]
+1

**Comment by akrohn** [comment]
+1

**Comment by petruseugene** [comment]
+1

**Comment by akrohn** [comment]
Seems the developer is not active anymore?!

**Comment by akrohn** [comment]
This issue is described too in the base project.

Changing the line:
`addtocalendar.load = ready(function () {`
 to:
`addtocalendar.load = function () {`

And changing:

```
    });
    addtocalendar.load();
```

to:

```
    };
    addtocalendar.load();
```

fixes the problem.

Hope this helps.

**Comment by throrin19** [comment]
Can you make a PR to fix this ?

**Comment by RyanMadsen** [comment]
Still broken today when I tried it, The @akrohn 's fix works though.

**Comment by TheAliAbbasi** [comment]
+1
yeap it definitely still has that bug

**Comment by lukemunn** [comment]
+1
still broken for me too. 

Uncaught TypeError: addtocalendar.load is not a function(…)(anonymous function) @ atc.min.js:1(anonymous function) @ atc.min.js:1

**Comment by S8nsick66** [comment]
+1 Still broken, same error message.
Using bower install in an Angular project.

It works with the unminified version.

**Comment by agilbert** [comment]
Still having this issue, also worked around it by using the unminified version.

**Comment by bhargav-sae** [comment]
- Still has a problem with Angular 2.

**Comment by aske-cph** [comment]
+1

**Comment by marcinkrzeminski** [comment]
Hi,

instead of installing it with:

```
npm install addtocalendar
```

I did this
```
npm install https://github.com/AddToCalendar/addtocalendar
```

and then included the unminfied version 
```
require('addtocalendar/addtocalendar.js');
```

and it works ;).

Hope that helps someone ;)

**Comment by blackredwhite** [comment]
Hey, if you've got it still the same problem. 
Try like that:
1. Load styles and script to your local server
2. Remove in addtocalendar.js (or minifed version) line addtocalendar.load();
3. When you load script load like this:
(function () {
    if (window.addtocalendar)if(typeof window.addtocalendar.start == "function")return;
})();

On my website working :)
